lint

The weave repo has some slight modifications to the lint script:
- they ignore lint errors about comments
- they aren't strict about test packages and file names
This changes adds ```-nocomment``` and ```-notestpackage``` arguments to the lint script, so weave can start to share the same script.

Add support for weave in lint script.

---

lint

Means we don't get spurious warnings from generated Javascript files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/build-tools/23)

Only lint git files

---

files-with-type
test

Updates a couple of the places where we use `find` to use `git ls-files` instead: it's faster and closer to what we actually want.
Updates shell linting to ignore vendoring. I'm not super happy with it, but I'd like to get this in quickly, get linting running on everything, *then* rewrite all this stuff in a real language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/build-tools/24)

Find files correctly

---

files-with-type
lint

Also, only run `shell-lint` over specified directories. Fixes build failures in scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/build-tools/26)

Properly exclude vendor from lint

---

image-tag

We have divergent versions of this script across repos.
This particular version comes from 6334836@scope.
We in particular want this version's changes to support branches
with a '/' character in them.
Once this PR is merged, we can begin making changes to other repos to use
this repo's version instead of their own.

Import image-tag script into build tools so it can be shared

---

integration/gce.sh

A harmless (for now) bug where `names` global was being modified when
a local was intended.

integrations: Fix a shellcheck linter error

---

shell-lint

This fixes the case where the provided paths do not contain any shell scripts,
ie. xargs is passed no values.
In this case by default, xargs invokes the command once with no args.
This causes shellcheck to print usage and exit failure.
The GNU-specific --no-run-if-empty changes the behaviour so that in this case,
shellcheck is simply never run.
This allows us to use this script as a general lint even in contexts where
no shell scripts are present, or none of the files passed are shell scripts.

shell-lint: Don't fail if no shell scripts found

---

runner/runner.go
socks/main.go

Temporary fix for https://github.com/weaveworks/build-tools/issues/38 
We should probably start using cobra instead.

Use mflag package from weaveworks fork until we find a better solution

---

rebuild-image

In the case of a force push, the commit will not exist anymore, and the
`git diff` in `has_changes` will fail, but the failure would be silently
ignored (since the error message would be passed to `wc`).
`wc -l` would return 1, so effectively the same image would be reused
over and over.

Check if SHA1 exists before calling `git diff`on it

---

integration/assert.sh
lint

Don't over write lint_result with 0 when shellcheck succeeds

---

test

If we don't assume tags=netgo, then we can use ./tools/test where we can't write to the go install (for instance, on your mac).

Make no-go-get the default, and don't assume -tags netgo

---

test

Reverts weaveworks/build-tools#61
Was causing issues like:
```
docker run  -ti \
-v /home/ubuntu/cortex/.pkg:/go/pkg \
-v /home/ubuntu/cortex:/go/src/github.com/weaveworks/cortex \
weaveworks/cortex-build test
make: Entering directory '/go/src/github.com/weaveworks/cortex'
protoc -I ./vendor:. --go_out=plugins=grpc:. ./cortex.proto
./tools/test -no-go-get
go install net: open /usr/local/go/pkg/linux_amd64/net.a: permission denied
Makefile:84: recipe for target 'test' failed
make: *** [test] Error 1
make: Leaving directory '/go/src/github.com/weaveworks/cortex'
make: *** [test] Error 2
make RM= test returned exit code 2
```

Revert "Make no-go-get the default, and don't assume -tags netgo"

---

lint

Having _test packages leads to unnecessary symbol exports

Remove test package linting

---

integration/config.sh

Broken as a side-effect of introducing shellscript linting
e.g: https://github.com/weaveworks/build-tools/commit/83d5bd1f0e0132a88f55aab71735f351548a2860#commitcomment-20521055

Fix integration tests

---

test

Given that we split repos when test suites take too long, we might as well lower the timeout that we use for tests.
This has the benefit of accelerating local development when encountering deadlocked or infinite looping code.

Reduce test timeout

---

lint

Lint-ing all of Weave Net is currently not desirable because: 
* it would create conflicts on many branches,
* it would pollute the git history, 
* etc. 
and because `lint` currently lints all files except `./vendor`, this breaks Weave Net's build.
As a result, Weave Net is not using the latest commit in `build-tools`'s `master` branch, which is also source of problems:
* it limits standardisation of projects across Weaveworks, 
* it limits the ability to use the latest features of `build-tools`, 
* it complexifies merging changes in `build-tools` (e.g. #53 and weaveworks/weave#2694 for weaveworks/weave#2647), 
* etc.
This change adds the ability to optionally process a `.lintignore` file, which can contain any number of `GLOB`s then used to filter out files one does not want to lint, …

Add support for .lintignore.

---

lint

On cortex, >60% saving.
```
Toms-MacBook-Pro:cortex twilkie$ time ./tools/lint 
push-images: run shfmt -i 4 -w push-images
tools/lint: run shfmt -i 4 -w tools/lint
real	0m10.466s
user	0m5.115s
sys	0m4.070s
Toms-MacBook-Pro:cortex twilkie$ time ./tools/lint -p
push-images: run shfmt -i 4 -w push-images
tools/lint: run shfmt -i 4 -w tools/lint
real	0m4.366s
user	0m7.121s
sys	0m5.434s
```

Add -p option to parallelise lint.

---

provisioning/setup.sh

This makes the setup.sh script work more consistently: 
- under both Linux and macOS, and 
- whether you source it or execute it.

Set current dir using BASH_SOURCE.

---

sched

The response.text and json-parsed string values are both unicode strings.
The print statement requires bytes, as per write(2).
Python is dumb and bad at converting between them properly - in the name of being "safe"
it errors if any non-ascii characters are present, so it works until it doesn't.
We fix this by explicitly encoding as utf-8.

sched: Fix unicode encoding issues

---

integration/config.sh
integration/gce.sh
integration/sanity_check.sh
provisioning/setup.sh

Please note: cc02224 assumes `integration/config.sh` is only used in the context of Scope's integration tests. Is that actually correct?
xref https://github.com/weaveworks/scope/pull/2225

integration/config: fix weave path etc.

---

integration/gce.sh

Should help prevent testing VMs to be used for DOS attacks.
N.B.: not tested.

Secure GCP servers for Scope.

---

config_management/group_vars/all
config_management/roles/dev-tools/tasks/main.yml
config_management/roles/docker-configuration/tasks/main.yml
config_management/roles/docker-from-docker-repo/tasks/debian.yml
config_management/roles/docker-from-docker-repo/tasks/redhat.yml
config_management/roles/docker-from-tarball/tasks/main.yml
config_management/roles/docker-prerequisites/tasks/debian.yml
config_management/roles/golang-from-tarball/tasks/main.yml
config_management/roles/kubelet-stop/tasks/main.yml
config_management/roles/kubernetes-install/tasks/debian.yml
config_management/roles/kubernetes-install/tasks/main.yml
config_management/roles/kubernetes-install/tasks/redhat.yml
config_management/roles/kubernetes-start/tasks/main.yml
config_management/roles/sock-shop/tasks/tasks.yml
config_management/roles/weave-kube/tasks/main.yml
config_management/roles/weave-net-sources/tasks/main.yml
config_management/roles/weave-net-utilities/tasks/main.yml
config_management/setup_weave-kube.yml
config_management/setup_weave-net_dev.yml
config_management/setup_weave-net_test.yml

@marccarre these are the changes I had to make to make our playbooks work with the current unstable packages... I've not attempted to clean this up, as I'm not sure what would be the best way to go about it.

Add support for "unstable" and 1.6 versions of Kubernetes to dev/test infrastructure

---

config_management/roles/docker-configuration/files/docker.conf
config_management/roles/docker-configuration/files/docker_over_tcp.conf
config_management/roles/docker-configuration/tasks/main.yml

The flag ensures that, when pulling from (or pushing to) a remote registry, HTTP instead of HTTPS used.
Otherwise, in Weave Net smoke tests we would need to setup CAs on each host.
Required by https://github.com/weaveworks/weave/pull/2727.

Add --insecure-registry to docker.conf

---

config_management/roles/kubernetes-start/tasks/main.yml
provisioning/setup.sh

**Changelog**:
- lock `kubeadm`'s Kubernetes version. Without this change, `kubeadm` typically upgrades whichever version of Kubernetes is installed, sometimes leading to conflicts in between components' version.
- improved usage for `tf_ansi` and `tf_ssh` helper commands.

Lock kubeadm's Kubernetes version.

---

build/haskell/Dockerfile
build/haskell/build.sh
build/haskell/copy-libraries

See https://github.com/weaveworks-experiments/compare-revisions/pull/1 for an illustration.
The reason it's all so complicated is that `stack` _already_ does dockerized builds (e.g. `stack --docker build`), so it's a matter of reverse engineering what it does.

Haskell build image

---

build/Makefile

Was failing because `[[:alpha:]]*` did not match `fpco/stack-build`.

broaden imagetag regex to fix haskell build image

---

config_management/group_vars/all
provisioning/setup.sh

In order to benefit from latest release's changes, e.g. `time.Until`.
See also: https://golang.org/doc/go1.8

Upgrade default Go version to 1.8.1.

---

build/golang/build.sh
build/haskell/build.sh
push-images

Needed for https://github.com/weaveworks/tcptracer-bpf/pull/38

Update for latest shfmt

---

integration/assert.sh
lint

The previous PR (https://github.com/weaveworks/build-tools/pull/95) missed some shfmt fixes. This PR also prints the shfmt diff: this will help to fix future shfmt issues.
This should fix the failures detected on https://circleci.com/gh/kinvolk/tcptracer-bpf/423. The CI is green on https://circleci.com/gh/kinvolk/tcptracer-bpf/426
Needed for
- https://github.com/weaveworks/tcptracer-bpf/pull/37
- https://github.com/weaveworks/tcptracer-bpf/pull/39
@2opremio PTAL

More shfmt updates

---

dependencies/list_os_images.sh
provisioning/setup.sh

Symptoms:
```
./tools/dependencies/list_os_images.sh:11:3: $ must be escaped or followed by a literal
./tools/provisioning/setup.sh:307:3: $ must be escaped or followed by a literal
```
Needed for https://github.com/weaveworks/tcptracer-bpf/pull/39

shellcheck: fix escaping issue

---

dependencies/cross_versions.py
dependencies/list_versions.py
sched

.. to allow use of virtual environments and install up-to-date
dependencies.
We stumbled over this when trying to update python-requests for the
Scope build-tools update which includes
https://github.com/weaveworks/build-tools/pull/73/commits/3e863df9bee7567300d3c2d11203ba0d182f7808
and expects python-requests >= 2.4.2.

Change Python shebang to `#!/usr/bin/env python`

---

test

So callers can pass in build tags.
This helps to ensure tests are run with the same tags as builds, and also avoids recompiling the code between build and test when the Go compiler sees the tags are different.

Add -tags option to test script

---

config_management/group_vars/all
config_management/roles/docker-configuration/files/docker.conf
config_management/roles/docker-from-docker-ce-repo/tasks/debian.yml
config_management/roles/docker-from-docker-ce-repo/tasks/main.yml
config_management/roles/docker-from-docker-ce-repo/tasks/redhat.yml
config_management/roles/docker-from-get.docker.com/tasks/debian.yml

Version 1.13, which we were using, no longer installs via get.docker.com
I couldn't figure out how to fix the 1.13 install, but it's a very small percentage of our users so I bumped the default to 17.06 and made that work, based on [Docker's instructions](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository)

Update Docker installation

---

config_management/roles/dev-tools/files/apt-daily.timer.conf
config_management/roles/dev-tools/tasks/main.yml

This slows down boot and is of questionable value when the machines are only going to live for a few minutes.  If you leave them on they will run the process daily.
Also we have seen the update process create a 'defunct' process which then throws off Weave Net smoke-test checks.

Override apt daily job to not run immediately on boot

---

push-images

@rade spotted that an image failed to push, but the build still succeeded.
We could use `wait -n` to wait for subshells, however that requries bash >= 4.3, and OSX still ships with 3.2.57.

Check for errors when pushing images in parallel

---

README.md
lint

to match what we actually do, since the old instructions don't work
this is finishing off #99

Update shfmt instructions and fix lint

---

lint

I investigated why `lint` took ~4 minutes on the `service-conf` repo; some of it was spell-check of PKI files and some of it was spell-checking files we'd already checked.
These changes (minus extra Python checking added elsewhere) take it down to 2 minutes.

Tune linter spell check

---

build/golang/Dockerfile
lint

Before this change any `gocyclo` issue did not return an error and builds using it weren't aborting.

Gocyclo should return error code if issues detected

---

build/golang/Dockerfile
lint

Reverts weaveworks/build-tools#120
`gocyclo` checks are deliberately optional and do not block the build. Totally open to changing this, but should be done after consultation w/ the whole team.

Revert "Gocyclo should return error code if issues detected"

---

build/Makefile
build/golang/Dockerfile
build/haskell/Dockerfile
rebuild-image
socks/Dockerfile
socks/Makefile

Why? What?
- This should ultimately help for image-to-code back references.
- `org.label-schema.*` labels are now deprecated, in favour of `org.opencontainers.image.*` labels.
See also: https://github.com/opencontainers/image-spec/blob/master/annotations.md#back-compatibility-with-label-schema
- `MAINTAINER` is deprecated, in favour of the `maintainer` label.
- Git revision (`git rev-parse HEAD`) is now injected at `docker build` time.
Testing:
```console
$ docker inspect quay.io/weaveworks/build-golang
[
{
[...]
"ContainerConfig": {
[...]
"Labels": {
"maintainer": "Weaveworks <help@weave.works>",
"org.opencontainers.image.revision": "248def1ba24b8c48dc05f8f46d0f4a9c2a671e5e",
"org.opencontainers.image.source": "https://github.com/weaveworks/build-tools/tree/master/build/golang", …
```

Add opencontainers labels to dockerfiles

---

provisioning/gcp/outputs.tf

We need those to install a Kubernetes cluster on GCP VMs

tools: Add private_ips to the terraform output

---

provisioning/gcp/main.tf

Required by weaveworks/wks#24.

Allow CI to access k8s API server on GCP instances

---

dependencies/list_os_images.sh

Using --regexp produces the warnings:
WARNING: Flag --regexp is deprecated. Use --filter="name~'REGEXP'" instead.
Still works!
$ ./tools/dependencies/list_os_images.sh gcp centos
centos-cloud/centos-6
centos-cloud/centos-7

tools: Use --filter instead of --regexp with gcloud

---

lint

Modified the lint tools to skip the shfmt check if not installed.
For ppc64le the specific version of shfmt is not available,
hence skipped completely the installation of shfmt tool. Thus this change made.

Changes to enable weave/scope for power 

---

socks/main.go

This is to re-do part of weaveworks/scope#3276 in the correct place

Update socks proxy: context is now part of the Go standard library

---

build/golang/Dockerfile
lint

Update the build image and lint script to work with Go 1.12
`go tool vet` has been removed upstream.
`go vet` does not accept a single filename to work on, so I have updated the script to vet a whole directory at once.

Update to Go 1.12.1

---

image-tag

Doing it the right way - see https://github.com/weaveworks/wks/pull/529#pullrequestreview-232163521 for more context.

Fix image-tag object name prefix length to 8 chars

---

.circleci/config.yml
build/golang/Dockerfile
cover/Makefile
lint
runner/Makefile
socks/Makefile
test

This in turn updated shellcheck, so we have a few fixes.
Also some build flags need to change on tools otherwise they crash.

Update Go build to 1.13.1

---

build/golang/Dockerfile

* Update Go to 1.13.5 (latest as of posting)
* Install python 3 instead of obsolete v2.7
* Pin the version of `attrs`
* Stop installing promtool - It's not used by most downstreams, and at least one that does overrides it with a different version.

Update Go build image to newer Go and Python

---

.circleci/config.yml
lint

This is a bit embarrasing: CI was running `lint` (ignoring the `.` that came after), and that did nothing, so constant success.
Fixing `lint` to do all directories when called on its own brought up other problems, which are addressed by doing things slightly differently in CI.

Fix lint script

---

dependencies/cross_versions.py
lint
scheduler/main.py

Fix bug where failure state did not get propagated to the final exit code.
Fix lint errors in Python code that were being hidden.
Skip entire directories that match filter patterns.
Also slight simplification of the zero-arguments case.
Note that filter patterns have to match `./foo/bar` which is different from what happened before #155

Improve lint filtering and error reporting

---

scheduler/requirements.txt

The flask version specified is not compatible with latest werkzeug.
I have already updated the live app using the instructions at #167

Restruct scheduler to use compatible version of werkzeug library
