- socks/README.md
Based on unpublished blogpost.
> added README for the socks proxy

- cover/gather_coverage.sh
- rebuild-image
> Compress cached images.

- socks/main.go
> socks: Make main shExpMatch expression configurable

- scheduler/main.py
Fixes #10
I haven't tried deploying this, so...
> Don't delete GCE nodes for running (but failed) builds

- integration/assert.sh
- integration/config.sh
- integration/gce.sh
- integration/run_all.sh
- integration/sanity_check.sh
- runner/runner.go
This is needed by https://github.com/weaveworks/scope/pull/807, and finally means scope doesn't depend on weave!
Also adds repo name to schedule for integration tests, so different repos don't clash.
See https://github.com/weaveworks/weave/issues/1286
> More gce scripts from weave into tools.

- lint
- rebuild-image
> Add misspell to the lint script.

- test
Move fast, break things, then fix them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/build-tools/25)
> Test directories need ./ prefixes, obviously.

- cmd/wcloud/cli.go
- cmd/wcloud/client.go
Fixes https://github.com/weaveworks/deploy/issues/25
> Add wcloud events, update flags and error nicely when there is no config

- cmd/wcloud/types.go
Matches: https://github.com/weaveworks/deploy/pull/63
> [wcloud] Add support for repo_branch option

- cmd/wcloud/cli.go
- cmd/wcloud/client.go
- cmd/wcloud/errors.go
- cmd/wcloud/types.go
wcloud side of https://github.com/weaveworks/service/pull/815
> Add experimental support for user tokens

- circle.yml
- vendor/github.com/mvdan/sh/LICENSE
- vendor/github.com/mvdan/sh/cmd/shfmt/main.go
- vendor/github.com/mvdan/sh/syntax/doc.go
- vendor/github.com/mvdan/sh/syntax/lexer.go
- vendor/github.com/mvdan/sh/syntax/nodes.go
- vendor/github.com/mvdan/sh/syntax/parser.go
- vendor/github.com/mvdan/sh/syntax/printer.go
- vendor/github.com/mvdan/sh/syntax/tokens.go
- vendor/github.com/mvdan/sh/syntax/walk.go
- vendor/manifest
Due to https://github.com/mvdan/sh/issues/47
> Try and vendor a specific version of shfmt

- scheduler/main.py
This is required so that VMs started by build-tools/provisioning against the weave-net-tests project in GCP are garbage collected, should an issue arise and therefore, should the VMs be kept up and running for no good reason.
This work is related to weaveworks/weave#2647 and weaveworks/build-tools#53.
> Scheduler now also garbage-collects VMs from weave-net-tests.

- scheduler/main.py
Introduced by https://github.com/weaveworks/weave/pull/2670
(I haven't figured out how to test this yet)
> Garbage-Collect firewall rules

- test
(Needs some more work, was reverted once)
> Test defaults

- config_management/README.md
* Some cleanup.
* Fix task file names.
* Use `ansible_inventory`.
cc @marccarre
> Fix config_management/README.md

- lint
> Add linter function to avoid bad merge/rebase artefact

- test
> Add no-race argument to test script

- dependencies/list_os_images.sh
- integration/assert.sh
> Update for latest shfmt

- build/golang/Dockerfile
- circle.yml
> Give up on versioned copy of shfmt; it doesn't build

- circle.yml
- dependencies/cross_versions.py
- dependencies/list_versions.py
- lint
- scheduler/main.py
> Add python linting

- image-tag
Should be faster for large changes!
> Use git status instead of diff to add 'WIP' tag

- integration/config.sh
Part of fixing weaveworks/weave#3035
> remove weaveplugin remnants

- config_management/README.md
There was no documentation of this aspect of the playbook so far.
This PR addresses that.
As always, feedback welcome on how clear/obscure this is.
> Document selection of Docker installation role

- build/golang/Dockerfile
- circle.yml
- push-images
Fixes https://github.com/weaveworks/build-tools/issues/111
> Add shellcheck to bring linting in line with scope

- test
This should help getting more information on failing/passing tests.
Can also be useful for CIT, to see the detailed of tests ran/failed/passed.
> Propagate verbose flag to 'go test'

- scheduler/main.py
Update the regexes to find all scope VMs
> Add regex to match scope VMs

- socks/main.go
Had a need to change the localhost:8000 to a different value, submitting PR in case this has value to others.
> Add arg flag override for destination socks host:port in pacfile.

- COPYING.LGPL-3
- LICENSE
document as well that integration/assert.sh (used during test runs)
is LGPL3 with only cosmetic modifications
> license: add Apache 2.0 license text

- sched
Retries network errors or internal server errors
> Add retries to sched util http calls

- scheduler/README.md
- scheduler/main.py
- scheduler/requirements.txt
Fixes weaveworks/wks/issues/41.
Currently rebased on top of `fix-build` / #142 in order to build successfully.
> Garbage-collect WKS test VMs and firewall rules

- provisioning/gcp/main.tf
- provisioning/gcp/outputs.tf
https://www.terraform.io/docs/providers/google/r/compute_instance.html
> update google_compute_instance arguments as per the latest documentation

- scheduler/main.py
> Renames circleci project wks -> wksctl after code move

- build/golang/Dockerfile
cc @bboreham for upgrading wksctl eventually
> Upgrade to Go 1.14.4

- build/golang/Dockerfile
- lint
- Replace hclfmt with terraform fmt
> Replace hclfmt with terraform fmt
